
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : ALumno Pago
//  @ File Name : Alumno.java
//  @ Date : 03/09/2021
//  @ Author : Escuderia Pro-Gamers

import java.io.*;
import java.util.*;

public class Alumno {
	private int matricula;
	private int numeroCreditos;
   
	public Alumno(int matricula, int numeroCreditos) {//metodo contructor alumno
	setMatricula(matricula);
   setNumeroCreditos(numeroCreditos);
	}
	
   public void setMatricula(int matricula){//metodo set matricula
   this.matricula=matricula;
   }
   
   public void setNumeroCreditos(int numeroCreditos){//metodo set creditos
   this.numeroCreditos=numeroCreditos;
   }
   
   public double getMatricula(){//metodo get de matricula
   return matricula;
   }
   
   public double getNumeroCreditos(){//metodo get de numerocreditos
   return numeroCreditos;
   }
	
	public double calcularTotal() {
	return getNumeroCreditos()*2300;
	}
	
	public String toString() {
	return "\nla matricula es: "+matricula+"\nCreditos ocupados: "+numeroCreditos+"\nY El total a pagar es de: "+calcularTotal();
	}
}

class Principal{
   public static void main(String arg[]){
   int matricula=Principal.obtenerMatricula();
   int creditos=Principal.obtenerCreditos();
   Alumno a1=new Alumno(matricula,creditos);
   System.out.println(a1);
   }
   
   public static int obtenerMatricula() {
	Scanner a=new Scanner(System.in);
   System.out.println("Dame la matricula: ");
   int matricula =a.nextInt();   
   return matricula;
	}
	
	public static int obtenerCreditos() {
	Scanner b=new Scanner(System.in);
   System.out.println("Dame los creditos: ");
   int cred =b.nextInt();   
   return cred;
	}
  }